---
- name: Basic system setup
  hosts: myservers
  become: yes
  tasks:
    - name: Create a user
      user:
        name: johndoe
        password: "{{ 'SecureP@ssw0rd' | password_hash('sha512') }}"
        state: present

    - name: Ensure SSH service is running
      service:
        name: ssh
        state: started
        enabled: yes

    - name: Add SSH key for the new user
      authorized_key:
        user: johndoe
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Install essential packages
      apt:
        name:
          - vim
          - htop
        state: present
      when: ansible_os_family == "Debian"

    - name: Install essential packages
      yum:
        name:
          - vim
          - htop
        state: present
      when: ansible_os_family == "RedHat"
